import { memo } from "react";
import {
  Activity,
  Award,
  BarChart3,
  Bell,
  Bookmark,
  BookOpen,
  Calendar,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  Clock3,
  Eye,
  EyeOff,
  FileText,
  Flame,
  Home,
  Layers,
  LockKeyhole,
  LogOut,
  Megaphone,
  Medal,
  Menu,
  MessageSquare,
  Microscope,
  Moon,
  Pencil,
  Plus,
  RotateCcw,
  Save,
  Search,
  Settings,
  Sparkles,
  Sun,
  Syringe,
  Target,
  Trophy,
  User,
  X,
  ArrowLeft,
  Maximize2,
  Highlighter,
  Eraser,
  Hand,
  Trash2,
  Minus,
  GripVertical,
  ChevronUp
} from "lucide-react";

const icons = {
  grip: GripVertical,
  "chevron-up": ChevronUp,
  minus: Minus,
  highlighter: Highlighter,
  eraser: Eraser,
  hand: Hand,
  trash: Trash2,
  "arrow-left": ArrowLeft,
  expand: Maximize2,
  activity: Activity,
  analytics: BarChart3,
  award: Award,
  bell: Bell,
  bookmark: Bookmark,
  "book-open": BookOpen,
  calendar: Calendar,
  check: CheckCircle2,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  help: CircleHelp,
  clock: Clock3,
  eye: Eye,
  "eye-off": EyeOff,
  file: FileText,
  flame: Flame,
  home: Home,
  layers: Layers,
  lock: LockKeyhole,
  logout: LogOut,
  megaphone: Megaphone,
  medal: Medal,
  menu: Menu,
  messages: MessageSquare,
  microscope: Microscope,
  moon: Moon,
  pencil: Pencil,
  plus: Plus,
  reset: RotateCcw,
  save: Save,
  search: Search,
  settings: Settings,
  sparkles: Sparkles,
  sun: Sun,
  syringe: Syringe,
  target: Target,
  trophy: Trophy,
  user: User,
  x: X
};

export const Icon = memo(function Icon({ name, size = 20, strokeWidth = 1.9, ...props }) {
  const Component = icons[name] || CircleHelp;
  return <Component aria-hidden="true" size={size} strokeWidth={strokeWidth} {...props} />;
});

